---
- name: "Crear_Grupos_Dinamita"
  become: yes
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - G_R1
    - G_R2
    - G_R3
    - G_R4
    - G_R5
    - G_R6
    - Dinamita
