---


- name: "Parciando listado de grupos secundarios: LIST_USUARIOS.GROUPS "
  set_fact: foo_item="{{ item.GROUPS.split(',') }}"
  with_items: "{{ LIST_USUARIOS  }}"
  register: foo_result
  

- name: "Cargando listado GruposToCreate"
  set_fact: GruposToCreate="{{ foo_result.results | map(attribute='ansible_facts.foo_item') | list }}"
  

- name: "Alta de groups Secundarios del usuario "
  become: yes
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ GruposToCreate }}"
  

- name: "Agregando group Primario del usuario "
  become: yes
  group:
    name: "{{ item.USERNAME }}"
    state: present
  with_items: "{{ LIST_USUARIOS }}"
  

    
- name: "Alta y/o Actualizacion del usuario"
  become: yes
  user:
    name: "{{ item.USERNAME }}"
    password: "{{ item.HASH }}"
    group: "{{ item.USERNAME }}"
    groups: "{{item.GROUPS}}"
    state: present
    append: yes
  with_items: "{{ LIST_USUARIOS }}"
